### ISSUE TITLE
upload all .acs into UHC server

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-extraction-loading#11]
## Action Items
- [x]  @her43 load all .acs to `\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\raw`  
- [ ] #12 
- [ ] verification of completion.

**Comment by ran-codes** [comment]
@her43 can you comment in this issue when you have uploaded the .acs files to `\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\raw`?

thanks!! 😸

**Comment by her43** [comment]
> @her43 can you comment in this issue when you have uploaded the .acs files to `\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\raw`?

Done!

**Comment by alinasmahl1** [comment]
@ran-codes @her43 thanks!!! I think it would be great for us three to meet at some point to start thinking through a bit where some of the functional coding for cleaning should sit-e.g. within DBT vs just in R.
